package com.etezaz.assessment_task_magma.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.etezaz.assessment_task_magma.model.db.table.BhAdsImageStatus;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bhAdsImageStatusDaoConfig;

    private final BhAdsImageStatusDao bhAdsImageStatusDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bhAdsImageStatusDaoConfig = daoConfigMap.get(BhAdsImageStatusDao.class).clone();
        bhAdsImageStatusDaoConfig.initIdentityScope(type);

        bhAdsImageStatusDao = new BhAdsImageStatusDao(bhAdsImageStatusDaoConfig, this);

        registerDao(BhAdsImageStatus.class, bhAdsImageStatusDao);
    }
    
    public void clear() {
        bhAdsImageStatusDaoConfig.clearIdentityScope();
    }

    public BhAdsImageStatusDao getBhAdsImageStatusDao() {
        return bhAdsImageStatusDao;
    }

}
